import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CircleHelp,
  Clock,
  Command,
  Download,
  Eye,
  EyeOff,
  File,
  FileQuestion,
  Filter,
  Image,
  Info,
  LayoutDashboard,
  ListFilter,
  Loader2,
  LogOut,
  Moon,
  MoreHorizontal,
  PanelLeft,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  User,
  X,
  type LucideIcon,
} from "lucide-react";
import type { ComponentType } from "react";

export const icons = {
  alert: AlertTriangle,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  calendar: Calendar,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  command: Command,
  dashboard: LayoutDashboard,
  download: Download,
  error: AlertTriangle,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileQuestion: FileQuestion,
  filter: Filter,
  help: CircleHelp,
  image: Image,
  info: Info,
  listFilter: ListFilter,
  loader: Loader2,
  logout: LogOut,
  moon: Moon,
  more: MoreHorizontal,
  panelLeft: PanelLeft,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  success: CircleCheck,
  sun: Sun,
  time: Clock,
  trash: Trash2,
  upload: Upload,
  user: User,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

// Future Hindu SVG icons can be registered here without changing component APIs.
export const hinduIconRegistry = {} satisfies Record<string, ComponentType<{ className?: string }>>;
